### ISSUE TITLE
Custom prometheus labels on queries

### ISSUE THREAD

**Issue by kaspernissen** [lunarway/humio_exporter#3]
It would be a nice addition with the option to specify a field-value to be set as a label on the corresponding metrics. 

I'm not completely sure, how to implement this, because we currently only support aggregate functions, and thereby removing the field information in the response. 

One suggestion would be to specify it in the queries.yaml
```
queries:
- query: k8s.labels.app=some_service | count()
  repo: repo
  interval: 30m
  metric_name: service_log_lines_total
  labels:
     service: some_service
```

This should just add the specified label set in the corresponding metric as follows:

```
service_log_lines_total{repo="repo", interval="30m", service="some_service"} 1234
```
