### ISSUE TITLE
HumioExporter crashes if aggregated query contains no rows

### ISSUE THREAD

**Issue by srindal** [lunarway/humio_exporter#30]
A Humio query that ends with a count() will produce 0 if no rows were found, but a query that ends with an avg() or a sum() will produce no result if no rows were found. The latter will cause the humioexporter to  crash. I suggest that the exporter either returns a zero, or removes the metric from the list of metrics until the query starts producing data.

**Comment by Crevil** [comment]
I'm unable to reproduce this case.

The following query produces a 0 metric as expected. Can you share a crash log or alike from the latest version?

```yaml
queries:
  - query: nothing=existing | sum(status)
    repo: humio
    interval: 1m
    metric_name: humio_status_sum
```
