### ISSUE TITLE
Convert interval to be an array of intervals

### ISSUE THREAD

**Issue by kaspernissen** [lunarway/humio_exporter#5]
If you want to perform the same query but aggregate at different intervals, it would be handy to provide a string array of intervals instead of just a string right now. 

Example now: 
```
queries:
- query: res.statusCode>=200 | count(field=context.userId, distinct=true)
  repo: services
  interval: 24h
  metric_name: active_app_users
- query: res.statusCode>=200 | count(field=context.userId, distinct=true)
  repo: services
  interval: 1h
  metric_name: active_app_users
- query: res.statusCode>=200 | count(field=context.userId, distinct=true)
  repo: services
  interval: 5m
  metric_name: active_app_users
- query:  res.statusCode>=200 | count(field=context.userId, distinct=true)
  repo: services
  interval: 1m
  metric_name: active_app_users
```

Would become with the same metrics output:
```
queries:
- query: res.statusCode>=200 | count(field=context.userId, distinct=true)
  repo: services
  interval: [1m, 5m, 1h, 24h]
  metric_name: active_app_users
```
